apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-service
  template:
    metadata:
      labels:
        app: shopping-service
    spec:
      containers:
        - name: go-shopping-app
          image: tomaslingotti/shopping-service
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-service-svc
spec:
  type: NodePort
  ports:
    - name: http
      port: 9090
      targetPort: 3000
  selector:
    app: shopping-service